# Generated by Django 5.2.4 on 2025-08-15 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_category_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
        migrations.RenameField(
            model_name='category',
            old_name='slug',
            new_name='category_slug',
        ),
        migrations.AddField(
            model_name='product',
            name='product_slug',
            field=models.SlugField(blank=True, max_length=200, null=True),
        ),
    ]
